/*
 * This file is generated by jOOQ.
 */
package edu.alma.teamleft.tables.records;


import edu.alma.teamleft.tables.Client;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientRecord extends TableRecordImpl<ClientRecord> implements Record8<Integer, String, String, LocalDate, LocalDateTime, LocalDate, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.client.client_id</code>.
     */
    public void setClientId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.client.client_id</code>.
     */
    public Integer getClientId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.client.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.client.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.client.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.client.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.client.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.client.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.client.datetime_of_entry</code>.
     */
    public void setDatetimeOfEntry(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.client.datetime_of_entry</code>.
     */
    public LocalDateTime getDatetimeOfEntry() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.client.prescreen_date</code>.
     */
    public void setPrescreenDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.client.prescreen_date</code>.
     */
    public LocalDate getPrescreenDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.client.dba_id</code>.
     */
    public void setDbaId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.client.dba_id</code>.
     */
    public Integer getDbaId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.client.hmis</code>.
     */
    public void setHmis(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.client.hmis</code>.
     */
    public Integer getHmis() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, LocalDate, LocalDateTime, LocalDate, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, LocalDate, LocalDateTime, LocalDate, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Client.CLIENT.CLIENT_ID;
    }

    @Override
    public Field<String> field2() {
        return Client.CLIENT.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return Client.CLIENT.LAST_NAME;
    }

    @Override
    public Field<LocalDate> field4() {
        return Client.CLIENT.DATE_OF_BIRTH;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Client.CLIENT.DATETIME_OF_ENTRY;
    }

    @Override
    public Field<LocalDate> field6() {
        return Client.CLIENT.PRESCREEN_DATE;
    }

    @Override
    public Field<Integer> field7() {
        return Client.CLIENT.DBA_ID;
    }

    @Override
    public Field<Integer> field8() {
        return Client.CLIENT.HMIS;
    }

    @Override
    public Integer component1() {
        return getClientId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public LocalDate component4() {
        return getDateOfBirth();
    }

    @Override
    public LocalDateTime component5() {
        return getDatetimeOfEntry();
    }

    @Override
    public LocalDate component6() {
        return getPrescreenDate();
    }

    @Override
    public Integer component7() {
        return getDbaId();
    }

    @Override
    public Integer component8() {
        return getHmis();
    }

    @Override
    public Integer value1() {
        return getClientId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public LocalDate value4() {
        return getDateOfBirth();
    }

    @Override
    public LocalDateTime value5() {
        return getDatetimeOfEntry();
    }

    @Override
    public LocalDate value6() {
        return getPrescreenDate();
    }

    @Override
    public Integer value7() {
        return getDbaId();
    }

    @Override
    public Integer value8() {
        return getHmis();
    }

    @Override
    public ClientRecord value1(Integer value) {
        setClientId(value);
        return this;
    }

    @Override
    public ClientRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ClientRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ClientRecord value4(LocalDate value) {
        setDateOfBirth(value);
        return this;
    }

    @Override
    public ClientRecord value5(LocalDateTime value) {
        setDatetimeOfEntry(value);
        return this;
    }

    @Override
    public ClientRecord value6(LocalDate value) {
        setPrescreenDate(value);
        return this;
    }

    @Override
    public ClientRecord value7(Integer value) {
        setDbaId(value);
        return this;
    }

    @Override
    public ClientRecord value8(Integer value) {
        setHmis(value);
        return this;
    }

    @Override
    public ClientRecord values(Integer value1, String value2, String value3, LocalDate value4, LocalDateTime value5, LocalDate value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Integer clientId, String firstName, String lastName, LocalDate dateOfBirth, LocalDateTime datetimeOfEntry, LocalDate prescreenDate, Integer dbaId, Integer hmis) {
        super(Client.CLIENT);

        setClientId(clientId);
        setFirstName(firstName);
        setLastName(lastName);
        setDateOfBirth(dateOfBirth);
        setDatetimeOfEntry(datetimeOfEntry);
        setPrescreenDate(prescreenDate);
        setDbaId(dbaId);
        setHmis(hmis);
    }
}
